#! /bin/bash

#./delayed-launcher /opt/origin/openshift.local.config/${NODE}/node-config.yaml 60

CONFIG=$1
INTERVAL=$2

sleep ${INTERVAL}
sudo systemctl start docker
sleep ${INTERVAL}
sudo /opt/origin/openshift start node \
  --config=${CONFIG} \
  --loglevel=5 >>/tmp/node.log 2>>/tmp/node.log &
