#! /bin/bash

MASTER_IP=192.168.1.10

if [[ -d openshift.local.config ]]; then
  rm -rf openshift.local.config
fi

./openshift start master --write-config=openshift.local.config/master \
  --master=${MASTER_IP}:8443

for i in `seq 20 29`; do
  NODE=192-168-1-$i;
  NODEIP=192.168.1.$i;
  ./oadm create-node-config --node-dir=openshift.local.config/ip-${NODE} \
    --node=ip-${NODE}.ec2.internal \
    --hostnames=ip-${NODE}.ec2.internal,${NODEIP} \
    --master=https://${MASTER_IP}:8443;
  ./mod-node-config.py openshift.local.config/ip-${NODE}/node-config.yaml
done
